### ISSUE TITLE
SMILES are missing in the datasets

### ISSUE THREAD

**Issue by piermichele-kobauri** [iouthwaite/inhibitor_combinations#1]
Hi, thank you very much for your extremely interesting work. I was checking the files available in full-datasets and I saw that the SMILES column is empty for all files except [PKIS2_dataset.xlsx](https://github.com/iouthwaite/inhibitor_combinations/blob/main/full-datasets/PKIS2_dataset.xlsx). Are you planning to provide these data as well? They would be very useful. :)

**Comment by iouthwaite** [comment]
Hello, thank you for your interest! Unfortunately we don't use SMILES, that column is leftover from the formatting of the original PKIS2 work. I would recommend that you look at the original publications for each of the datasets to retrieve SMILES for the compounds. For example, SMILES for the compounds in Klaeger _et al_ (2017) are available in supplement table 1 for that publication.

Please let me know if this resolves this issue, if so I'll close this thread.

**Comment by piermichele-kobauri** [comment]
Ok, I will do that. Thank you for your quick reply!

**Comment by iouthwaite** [comment]
No problem, happy to help! 

Closing thread.
